obj-m += sentinel_mod.o

KDIR ?= /lib/modules/$(shell uname -r)/build

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean

install:
	sudo insmod sentinel_mod.ko

uninstall:
	sudo rmmod sentinel_mod

.PHONY: all clean install uninstall
